#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  /Users/rodoyle/.cargo/bin
  $path
)
export RUST_SRC_PATH=/Users/rodoyle/src/rust/src

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

## PyEnv
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# rsync
alias beastsync='rsync -avz --exclude-from=exclude-list.txt --delete  ~/src/deskgen/dgsource rileyd@192.168.2.25:/home/rileyd/src/deskgen --delete'

# VI bindings
export KEYTIMEOUT=1

# The next line updates PATH for the Google Cloud SDK.
if [ -f /Users/rodoyle/Downloads/google-cloud-sdk/path.zsh.inc ]; then
  source '/Users/rodoyle/Downloads/google-cloud-sdk/path.zsh.inc'
fi

# The next line enables shell command completion for gcloud.
if [ -f /Users/rodoyle/Downloads/google-cloud-sdk/completion.zsh.inc ]; then
  source '/Users/rodoyle/Downloads/google-cloud-sdk/completion.zsh.inc'
fi
